version: '3.8'

networks:
  external_net: {}

services:
  marklogic:
    image: store/marklogicdb/marklogic-server:${mlVersionTag}
    extra_hosts:
      host.docker.internal: host-gateway
    ports:
        - "${mlSystemPortMapping}"
        - "${mlApplicationPortMapping}"
    hostname: "${mlHost}"
    container_name: "${mlHost}"
    environment:
      - MARKLOGIC_INIT=true
      - MARKLOGIC_ADMIN_USERNAME=${mlAdmin}
      - MARKLOGIC_ADMIN_PASSWORD=${mlPassword}
      - TZ=Europe/Amsterdam
    volumes:
      - assets:/var/opt/MarkLogic
      - ${dockerData}/LVBB/${mlHost}/Logs/:/var/opt/MarkLogic/Logs/:delegated
      - ${projectVolume}:/mnt/project
    networks:
      - external_net
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: 16G

volumes:
  assets:
